os: linux

language: python
python: "3.5"

branches:
    only: master

env:
    matrix:
        - TASK=fmt-travis
        - TASK=lint
        - TASK=test
        - TASK=coverage

script: make -f Makefile $TASK
